# Generated by Django 3.1.4 on 2021-02-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0002_auto_20210205_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='descrirption',
            new_name='description',
        ),
    ]
