# Generated by Django 3.1.4 on 2021-02-06 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0008_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
