# Generated by Django 3.1.4 on 2021-02-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0009_recentpost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recentpost',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
