# Generated by Django 3.1.4 on 2021-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0010_auto_20210206_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='description',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
