# Generated by Django 3.1.5 on 2021-02-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0011_recentpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='submit_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
