# Generated by Django 3.1.5 on 2021-02-06 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0013_auto_20210206_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
