# Generated by Django 3.1.5 on 2021-02-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0014_post_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
