# Generated by Django 3.1.5 on 2021-02-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0015_auto_20210206_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(),
        ),
    ]
