# Generated by Django 3.1.5 on 2021-02-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0019_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
