# Generated by Django 3.1.5 on 2021-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0020_auto_20210206_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentpost',
            name='description',
        ),
        migrations.AlterField(
            model_name='recentpost',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
