# Generated by Django 3.1.5 on 2021-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0022_auto_20210206_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentpost',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
