# Generated by Django 3.1.5 on 2021-02-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0023_auto_20210206_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentpost',
            options={'ordering': ['-pub_date']},
        ),
    ]
