# Generated by Django 3.1.5 on 2021-02-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0025_auto_20210209_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
