# Generated by Django 3.1.5 on 2021-02-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0027_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='duapost',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='duaspost_comments', to='urduweb.duaspost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='urduweb.post'),
        ),
    ]
