# Generated by Django 3.1.5 on 2021-02-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0028_auto_20210216_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='duapost',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='urduweb.duaspost'),
        ),
    ]
