# Generated by Django 3.1.5 on 2021-02-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0029_auto_20210216_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='duapost',
        ),
    ]
