# Generated by Django 3.1.5 on 2021-02-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0030_remove_comment_duapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='duapost',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='urduweb.duaspost'),
        ),
    ]
