# Generated by Django 3.1.5 on 2021-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0034_auto_20210217_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Articles', max_length=255),
        ),
    ]
