# Generated by Django 3.1.5 on 2021-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0035_auto_20210217_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
