# Generated by Django 3.1.5 on 2021-02-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0038_auto_20210217_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='duapost',
        ),
    ]
