# Generated by Django 3.1.5 on 2021-02-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0039_remove_comment_duapost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuasPost',
        ),
        migrations.DeleteModel(
            name='PeotyPost',
        ),
        migrations.DeleteModel(
            name='RecentPost',
        ),
    ]
