# Generated by Django 3.1.5 on 2021-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urduweb', '0041_post_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
